# fly.toml app configuration file generated for vic-datingapp on 2023-04-27T11:55:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vic-datingapp"
primary_region = "sea"

[build]
  image = "jianmingtu/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="drtqyhve5"
  CloudinarySettings__ApiKey="837992371395812"    

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
